# docker-compose.yml
version: '3.8'

services:
  my-node-app:
    image: my-node-app
    build:
      context: .
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    restart: always
